#!/bin/bash


gcc -std=c11 -fPIC -c -I ../lib/clingo/libclingo \
    -I ../lib/godot_headers clingoTest.c -o clingoTest.os \
    -L/home/dario/data/uni/5semester/agentTechnology/blocksWorldPlanning/godotProject/lib/clingo/build/bin \
    -lclingo

gcc -shared clingoTest.os -o clingoTest.so \
    -Wl,-rpath= /home/dario/data/uni/5semester/agentTechnology/blocksWorldPlanning/godotProject/lib/clingo/build/bin/libclingo.so \
    -Wl,-rpath=/home/dario/data/uni/5semester/agentTechnology/blocksWorldPlanning/godotProject/lib/clingo/build/bin/
